services:
  food-justice-teacher-service:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - RENPY_GAME_DIR=SciStoryTeacherDemo
    image: ${IMAGE_NAME:-foodjustice-teacher-demo}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-foodjustice-container-teacher-demo}
    ports:
      - "${EXTERNAL_PORT:-8081}:8080"
    environment:
      - GAME_ROOT_DIR=/code/SciStoryTeacherDemo
    volumes:
      - SciStoryPollinatorsTeachersDemo:/code/gamelogs
      - $HOME/.env.appteacher:/code/.env.app
      - $HOME/.env.syncflowteacher:/code/.env.syncflow

  
volumes:
  SciStoryPollinatorsTeachersDemo: