services:
  food-justice-service:
    build: .
    image: foodjustice:latest
    container_name: "foodjustice-container"
    ports:
      - "8080:8080"
    environment:
      - GAME_ROOT_DIR=/code/SciStoryPollinators
    volumes:
      - SciStoryPollinators:/code/gamelogs
      - $HOME/.env.foodjustice:/code/.env.app
      - $HOME/.env.foodjustice:/code/.env.syncflow

  
volumes:
  SciStoryPollinators: