services:
  food-justice-service:
    build:
     context: .
     dockerfile: Dockerfile
     args:
        - RENPY_GAME_DIR=SciStoryPollinators
    image: foodjustice:latest
    container_name: "foodjustice-container"
    ports:
      - "${EXTERNAL_PORT:8080}:8080"
    environment:
      - GAME_ROOT_DIR=/code/SciStoryPollinators
    volumes:
      - SciStoryPollinators:/code/gamelogs
      - $HOME/.env.app:/code/.env.app
      - $HOME/.env.syncflow:/code/.env.syncflow

  
volumes:
  SciStoryPollinators: